name: Test and deploy Article Extractor to AWS ECR.

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: 357883163469.dkr.ecr.us-east-1.amazonaws.com
  REPOSITORY: multiprocessing-batch-extractor
  IMAGE_TAG: latest

jobs:
  lint:
    name: Lint Article Extractor
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    steps:

    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      id: install-flake8
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
    - name: Analysing the code with pylint
      id: run-flake8
      run: |
        python -m flake8 extractor

  test-and-deploy:
    name: Build and test Article Extractor image.
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Build and Push Base Image
      uses: docker/build-push-action@v2.10.0
      with:
        context: .
        platforms: linux/amd64
        push: false
        tags: |
        ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}

    - name: Run unit tests
      id: docker-run-pytest
      run: |
        docker run --entrypoint=./test.sh \
          -e AWS_ACCESS_KEY_ID=${{ secrets.EXTRACTOR_GITHUB_USER_KEY }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.EXTRACTOR_GITHUB_USER_SECRET }} \
          ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
    
    - name: Configure AWS Credentials
      id: configure-aws
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.EXTRACTOR_GITHUB_USER_KEY }}
        aws-secret-access-key: ${{ secrets.EXTRACTOR_GITHUB_USER_SECRET }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag and push image to Amazon ECR
      id: push-to-ecr
      run: |
        docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}